### ISSUE TITLE
Running stage up command with passphrase on SSH key errors

### ISSUE THREAD

**Issue by emmahsax** [dispatchitinc/ninny#30]
Running `ninny stage_up` when a passphrase is set on the SSH key used results in error:

```
$ ninny stage up
Enter passphrase for key '/Users/firstnamelastname/.ssh/id_ed25519':
Checking out staging.2022.07.03.
Enter passphrase for key '/Users/firstnamelastname/.ssh/id_ed25519':
Enter passphrase for key '/Users/firstnamelastname/.ssh/id_ed25519':
/Users/firstnamelastname/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/gitlab-4.18.0/lib/gitlab/request.rb:71:in `validate': Server responded with code 400, message: merge_request_iid is invalid. Request URI: https://gitlab.com/api/v4/projects/4438192/merge_requests/up (Gitlab::Error::BadRequest)
	from /Users/firstnamelastname/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/gitlab-4.18.0/lib/gitlab/request.rb:55:in `block (2 levels) in <class:Request>'
	from /Users/firstnamelastname/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/gitlab-4.18.0/lib/gitlab/client/merge_requests.rb:47:in `merge_request'
	from /Users/firstnamelastname/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/ninny-0.1.22/lib/ninny/repository/gitlab.rb:38:in `pull_request'
	from /Users/firstnamelastname/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/ninny-0.1.22/lib/ninny/commands/pull_request_merge.rb:79:in `pull_request'
	from /Users/firstnamelastname/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/ninny-0.1.22/lib/ninny/commands/pull_request_merge.rb:55:in `merge_pull_request'
	from /Users/firstnamelastname/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/ninny-0.1.22/lib/ninny/commands/pull_request_merge.rb:28:in `execute'
	from /Users/firstnamelastname/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/ninny-0.1.22/lib/ninny/cli.rb:41:in `stage_up'
	from /Users/firstnamelastname/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/firstnamelastname/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/firstnamelastname/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/firstnamelastname/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /Users/firstnamelastname/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/ninny-0.1.22/exe/ninny:15:in `<top (required)>'
	from /Users/firstnamelastname/.rbenv/versions/3.0.4/bin/ninny:25:in `load'
	from /Users/firstnamelastname/.rbenv/versions/3.0.4/bin/ninny:25:in `<main>'
```

My thoughts are that by typing in the passphrase, it ends up passing the passphrase into the merger as the `merge_request_iid`.

**Comment by emmahsax** [comment]
Closing due to archival.
